#!/usr/bin/env python3
import atexit
import argparse
from functools import cached_property
import enum
import re
from pathlib import Path
import signal
import subprocess
import sys
import time

from typing import Any, Generator, List, Tuple, Set
from collections.abc import Collection, Sequence

LOCKED_FILE_LOOP_SECONDS = 0.1
RENAME_COOLDOWN = 0.1

NUMBER_PREFIX = re.compile("^[0-9]+")


class FileAction(enum.Enum):
    CREATE = "CREATE"
    MOVED_FROM = "MOVED_FROM"
    MOVED_TO = "MOVED_TO"


class NumberedPath(Path):
    """A path that may follow the form \\d+.ext or \\d+-\\d+.ext"""

    @cached_property
    def numbers(self) -> Tuple[int, int] | Tuple[int, None] | Tuple[None, None]:
        """Returns the number component of the filename."""
        prefix = self.name.split(".")[0]
        parts = prefix.split("-")
        # File can only have a single number or two numbers separated by a hyphen.
        if len(parts) > 2:
            return None, None

        # First number
        if not parts[0].isdigit():
            return None, None
        first_num = int(parts[0])

        # Second number
        if len(parts) < 2 or not parts[1].isdigit():
            return first_num, None
        return first_num, int(parts[1])

    @property
    def number(self) -> int | None:
        """Returns the file number."""
        return self.numbers[0]

    @property
    def subnumber(self) -> int | None:
        """Returns the file subnumber."""
        return self.numbers[1]

    @property
    def number_always(self) -> int:
        """Same as .number, but throws an exception if None."""
        assert self.number is not None
        return self.number

    @property
    def subnumber_always(self) -> int:
        """Same as .subnumber, but throws an exception if None."""
        assert self.subnumber is not None
        return self.subnumber

    @property
    def is_numbered(self) -> bool:
        """Returns true if the filename is \\d+ or \\d+-\\d+"""
        return self.numbers[0] is not None

    @property
    def is_subnumbered(self) -> bool:
        """Returns true if the file is \\d+-\\d+"""
        return self.numbers[1] is not None


def autorename_files(args: Any) -> None:
    """Autorename files in a folder to be numbered sequentially."""
    extension_pattern = extensions_to_regex(args.extensions)
    last_renamed = None
    last_rename_time = 0

    for file, _, event_time in watch_directory(args.folder, extension_pattern):
        renames: List[Tuple[NumberedPath, NumberedPath]] = []

        print(f"Change detected for {file}", end="")
        numbered_paths = get_numbered(file.parent, extension_pattern, file)
        next_num = get_next_number(numbered_paths)

        # Ignore files that already fit in
        if file.number is not None and file.number <= next_num:
            print(" (already numbered).")
            continue

        # If we've haven't renamed recently, just rename it to the next number
        if not last_renamed or event_time > last_rename_time + args.pairing_window:
            new_path = file.parent / f"{next_num}{''.join(file.suffixes)}"
            renames.append((file, new_path))

        # Otherwise, subnumber it
        else:
            # Filter to just files with the current number
            curr_num = get_current_number(numbered_paths)
            curr_num_paths = [x for x in numbered_paths if x.number == curr_num]
            next_subnum = get_next_subnumber(curr_num_paths)

            # If there's a non-subnumbered file, subnumber it
            for path in curr_num_paths:
                if not path.is_subnumbered:
                    new_path = (
                        path.parent
                        / f"{curr_num}-{next_subnum}{''.join(path.suffixes)}"
                    )
                    renames.append((path, new_path))
                    next_subnum += 1

            # New name for current file
            new_path = file.parent / f"{curr_num}-{next_subnum}{''.join(file.suffixes)}"
            renames.append((file, new_path))

        # Actually execute the renames
        for old_path, new_path in renames:
            if rename_file(old_path, new_path):
                last_renamed = new_path
                last_rename_time = event_time
        print(".")


def rename_file(source: Path, target: Path) -> bool:
    """Renames a file. Returns true if the file was renamed."""
    print(f", {source} -> {target}", end="")

    # Skip if the target is the same as the source.
    if source == target:
        print(f" (same path)")
        return False

    # Run the last checks before renaming the file
    wait_for_file_locks(source)

    # Skip if the source doesn't exist
    if not source.exists():
        print(" (source does not exist after lock wait)")
        return False

    # Raise error if the target already exists
    if target.exists():
        raise RuntimeError(
            f"Unable to rename {source.name} -> {target.name}: "
            f"{target.name} already exists."
        )

    # Rename the file
    source.rename(target)
    return True


# Numbering


def get_numbered(
    folder: Path,  # The folder to check for files in.
    extension_pattern: re.Pattern,  # The file extensions to filter on.
    ignore: Path,  # A path to ignore in the results
) -> Set[NumberedPath]:
    """Returns all numbered directories and files in a path."""
    paths = set()
    for x in folder.glob("*"):
        x = NumberedPath(x)
        if not x.is_numbered or x == ignore:
            continue
        if not extension_pattern.search(x.name):
            continue
        paths.add(x)
    return paths


def get_current_number(paths: Collection[NumberedPath]) -> int:
    """Returns what the current number is, given a set of numbered paths."""
    if len(paths) == 0:
        return 0
    return max(x.number_always for x in paths)


def get_next_number(paths: Collection[NumberedPath]) -> int:
    """Returns what the next number should be, given a set of numbered paths."""
    if len(paths) == 0:
        return 0
    return get_current_number(paths) + 1


def get_next_subnumber(paths: Collection[NumberedPath]) -> int:
    """Returns what the next subnumber should be, given a set of numbered paths."""
    if len(paths) == 0:
        return 0
    # Ensure all paths have the same number
    first = next(iter(paths))
    assert all(
        x.number == first.number for x in paths
    ), "Subnumber can only be computed on paths with the same number."
    # If there is an un-subnumbered file, pretend it's a -1 subnumber
    # (meaning that -0 is the next subnumber)
    return max(x.subnumber or -1 for x in paths) + 1


# File monitoring


def watch_directory(
    folder: Path,  # The folder to monitor.
    extension_pattern: re.Pattern,  # The file extensions to monitor.
) -> Generator[Tuple[NumberedPath, FileAction, float], None, None]:
    """Yields files, the action performed, and the time as they are
    added/moved to the directory."""

    last_move_from_time = 0
    for path, action, event_time in watch_directory_with_inotifywait(
        folder, extension_pattern
    ):
        # Renaming is a move from + to, so note the time if moved away...
        if action == FileAction.MOVED_FROM:
            last_move_from_time = event_time
            continue
        # ...and ignore files that were renamed inside the folder
        if (
            action == FileAction.MOVED_TO
            and last_move_from_time > event_time - RENAME_COOLDOWN
        ):
            last_move_from_time = 0
            continue
        last_move_from_time = 0
        # Yield the event because it's a new file or something moved in
        yield path, action, event_time


def watch_directory_with_inotifywait(
    folder: Path,  # The folder to monitor.
    extension_pattern: re.Pattern,  # The file extensions to monitor.
) -> Generator[Tuple[NumberedPath, FileAction, float], None, None]:
    """Returns the command needed to watch a directory."""
    command = [
        "inotifywait",
        "--monitor",
        "--event",
        "create,moved_from,moved_to",
        "--includei",
        extension_pattern.pattern,
        "--format",
        "%w%f,%e",
        "--timefmt",
        "%s",
        str(folder),
    ]
    for line in run_command(command):
        split = line.split(",")
        yield NumberedPath(split[0]), FileAction(split[1]), time.time()


def wait_for_file_locks(file: Path) -> None:
    """Waits until no processes are currently using a file."""
    first_attempt = True
    while True:
        try:
            for _ in run_command(("fuser", str(file)), stderr=subprocess.DEVNULL):
                pass
            if first_attempt:
                print(f"{file.name} is in use by another process, waiting...")
                first_attempt = False
            time.sleep(LOCKED_FILE_LOOP_SECONDS)
        except subprocess.SubprocessError:
            if not first_attempt:
                print(f"{file.name} unlocked.")
            return


# I/O


def extensions_to_regex(extensions: Collection[str]) -> re.Pattern:
    """Converts a set of extensions into a regex pattern that matches files with
    those extensions. Matches everything if extensions is empty."""
    # Just match the end of the line if nothing is passed
    if len(extensions) == 0:
        return re.compile("$")
    # Convert all extensions into individual regex patterns...
    temp = set(f"\\.{x.removeprefix(".")}$" for x in extensions)
    # ...and join them together
    return re.compile("|".join(temp))


def run_command(command: Sequence[str], stderr=None) -> Generator[str, None, None]:
    """Runs a command, yielding each line of output."""
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=stderr)
    atexit.register(lambda: process.send_signal(signal.SIGTERM))

    # Yield each line of the command
    if process.stdout is not None:
        for line in iter(process.stdout.readline, b""):
            yield line.rstrip().decode("utf-8")

    # Exit unsuccessfully if the subprocess did
    process.communicate()
    if process.returncode != 0:
        raise subprocess.SubprocessError(
            f"Command {command} exited with exit code {process.returncode}."
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog=Path(__file__).name)
    parser.add_argument(
        "--pairing-window",
        type=float,
        default=-1,
        help='(Default: disabled) The number of seconds between autonaming files where they will be considered a "pair" and given the same base name.',
    )
    parser.add_argument("folder", type=Path, help="The folder to monitor for changes")
    parser.add_argument(
        "extensions",
        type=str,
        nargs="*",
        help="(Default: all files) File extensions to limit renaming to.",
    )
    args = parser.parse_args(sys.argv[1:])

    try:
        autorename_files(args)
    except KeyboardInterrupt:
        print(" Interrupting...")
