#!/usr/bin/env python3
import atexit
import argparse
from collections import defaultdict
from functools import cached_property
import enum
import re
from pathlib import Path
import signal
import subprocess
import sys
import time

from typing import Any, Dict, Generator, List, Tuple, Set
from collections.abc import Collection, Sequence

LOCKED_FILE_LOOP_SECONDS = 0.1
RENAME_COOLDOWN = 0.1

NUMBER_PREFIX = re.compile("^[0-9]+")


class FileAction(enum.Enum):
    CREATE = "CREATE"
    MOVED_FROM = "MOVED_FROM"
    MOVED_TO = "MOVED_TO"


class NumberedPath(Path):
    """A path that may follow the form \\d+.ext or \\d+-\\d+.ext"""

    @property
    def suffixes_str(self) -> str:
        """Returns self.suffixes as a string."""
        return "".join(self.suffixes)

    @cached_property
    def numbers(self) -> Tuple[int, int] | Tuple[int, None] | Tuple[None, None]:
        """Returns the number component of the filename."""
        prefix = self.name.split(".")[0]
        parts = prefix.split("-")
        # File can only have a single number or two numbers separated by a hyphen.
        if len(parts) > 2:
            return None, None

        # First number
        if not parts[0].isdigit():
            return None, None
        first_num = int(parts[0])

        # Second number
        if len(parts) < 2 or not parts[1].isdigit():
            return first_num, None
        return first_num, int(parts[1])

    @property
    def number(self) -> int | None:
        """Returns the file number."""
        return self.numbers[0]

    @property
    def subnumber(self) -> int | None:
        """Returns the file subnumber."""
        return self.numbers[1]

    @property
    def number_always(self) -> int:
        """Same as .number, but throws an exception if None."""
        assert self.number is not None
        return self.number

    @property
    def subnumber_always(self) -> int:
        """Same as .subnumber, but throws an exception if None."""
        assert self.subnumber is not None
        return self.subnumber

    @property
    def is_numbered(self) -> bool:
        """Returns true if the filename is \\d+ or \\d+-\\d+"""
        return self.numbers[0] is not None

    @property
    def is_subnumbered(self) -> bool:
        """Returns true if the file is \\d+-\\d+"""
        return self.numbers[1] is not None

    def get_numbered_children(
        self,
        extension_pattern: re.Pattern,  # The file extensions to filter on.
        ignore: Path | None = None,  # A path to ignore in the results
    ) -> Set[NumberedPath]:
        """Returns all numbered directories and files in a path."""
        paths = set()
        for x in self.glob("*"):
            x = NumberedPath(x)
            if not x.is_numbered or x == ignore:
                continue
            if x.is_file() and not extension_pattern.search(x.name):
                continue
            if x.is_dir() and x.suffix != "":
                continue
            paths.add(x)
        return paths


class Renamer:
    """A class for renaming files in a folder."""

    def __init__(self, args: Any):
        self.__pairing_window = args.pairing_window
        self.__extension_pattern = args.extensions_regex
        self.__last_event_time = 0
        self.__last_rename_time = 0
        self.__renamed_files = []

    def handle_file_event(self, file: NumberedPath, event_time: float) -> None:
        """Handles a file event for renaming."""
        print(f"Change detected for {file}", end="")

        self.__last_event_time = event_time
        numbered_paths = file.parent.get_numbered_children(
            self.__extension_pattern, file
        )
        next_num = get_next_number(numbered_paths)

        # Ignore files that already fit in
        if file.number is not None and file.number <= next_num:
            print(" (already numbered)", end="")
            return

        # If we've haven't renamed recently, just rename it to the next number
        if event_time > self.__last_rename_time + self.__pairing_window:
            self.rename(file, next_num)

        # Otherwise, subnumber it
        else:
            # Filter to just files with the current number
            curr_num = get_current_number(numbered_paths)
            curr_num_paths = [x for x in numbered_paths if x.number == curr_num]
            next_subnum = get_next_subnumber(curr_num_paths)

            # Subnumber preexisting files
            for path in curr_num_paths:
                if not path.is_subnumbered:
                    self.rename(path, curr_num, next_subnum)
                    next_subnum += 1

            # New name for current file
            self.rename(file, curr_num, next_subnum)
        print()

    def rename(self, source: NumberedPath, num: int, subnum: int | None = None) -> None:
        """Adds rename to a list of renames."""
        # Figure out what we're naming it
        if subnum is None:
            target = source.parent / f"{num}{source.suffixes_str}"
        else:
            target = source.parent / f"{num}-{subnum}{source.suffixes_str}"
        print(f", {source} -> {target}", end="")

        # Skip if the target is the same as the source.
        if source == target:
            print(f" (same path)", end="")
            return

        # Ensure something else isn't currently working with the file
        wait_for_file_locks(source)

        # Skip if the source doesn't exist anymore
        if not source.exists():
            print(" (source does not exist after lock wait)", end="")
            return

        # Raise error if the target already exists
        if target.exists():
            raise RuntimeError(
                f"Unable to rename {source.name} -> {target.name}: "
                f"{target.name} already exists."
            )

        # Rename the file
        source.rename(target)
        self.__last_rename_time = self.__last_event_time
        self.__renamed_files.append(target)

    def get_renamed_files(self) -> List[NumberedPath]:
        """Returns the paths the renamer has renamed since this function was
        last called."""
        files = self.__renamed_files
        self.__renamed_files = []
        return files


class Chunker:
    """A class for chunking renamed files into subfolders."""

    def __init__(self, args: Any):
        self.__root_path = NumberedPath(args.folder)
        self.__chunk_size = args.chunk_size
        self.__extensions_regex = args.extensions_regex

    def handle_file_event(self, renamed_files: List[NumberedPath]) -> None:
        """Handles a file event."""
        # Chunker disabled
        if self.__chunk_size <= 0:
            return
        # Didn't do anything in folder
        if not any(self.__root_path == x.parent for x in renamed_files):
            return
        # Chunk!
        chunked_files, chunk_dirs = self.__get_chunked_paths()
        self.__execute_chunking(chunked_files, chunk_dirs)


    def __get_chunked_paths(self) -> Tuple[Dict[int, List[NumberedPath]], Dict[int, NumberedPath]]:
        """Returns dicts of files and directories for each chunk."""
        children = self.__root_path.get_numbered_children(self.__extensions_regex)

        # Split dirs and files based on their chunk
        chunked_files = defaultdict(list)
        chunk_dirs = {}
        for path in children:
            start, end = self.__chunk_range(path)
            # Sort files into chunks
            if path.is_file():
                chunked_files[start].append(path)
            # Track which folder is responsible for which chunk
            elif path.is_dir():
                # Ensure no duplicate chunks
                if start in chunk_dirs:
                    raise RuntimeError(
                        "Multiple dirs for the same chunk: "
                        f"{chunk_dirs[start]} and {path}"
                    )
                # Ensure no mismatched chunk ranges
                path_start, path_end = path.number, path.subnumber
                if (path_start, path_end) != (start, end):
                    raise RuntimeError(
                        f"Chunk folder {path} is for range "
                        f"{path.number} -> {path.subnumber}, instead of the "
                        f"expected {start} -> {end}"
                    )
                chunk_dirs[start] = path

        return chunked_files, chunk_dirs

    def __execute_chunking(
        self,
        chunked_files: Dict[int, List[NumberedPath]],
        chunk_dirs: Dict[int, NumberedPath],
    ) -> None:
        """Moves files into chunk dirs."""
        # No files to chunk
        if len(chunked_files) <= 1:
            return

        largest_chunk = max(chunked_files.keys())

        print("Chunking", end="")
        for start, files in sorted(chunked_files.items()):
            end = start + self.__chunk_size - 1

            # Leave files for current chunk at the top level
            if start == largest_chunk:
                continue

            # Ensure chunk folder exists
            if start in chunk_dirs:
                chunk_dir = chunk_dirs[start]
            else:
                start, end = self.__chunk_range(files[0])
                chunk_dir = self.__root_path / f"{start}-{end}"
                print(f", + {chunk_dir}", end="")
                chunk_dir.mkdir(exist_ok=False)

            # Move files to chunk dir
            print(f", {self.__root_path}/{start}-{end} -> {chunk_dir}")
            for file in files:
                file.rename(chunk_dir / file.name)

    # Helpers

    def __chunk_range(self, path: NumberedPath) -> Tuple[int, int]:
        """Computes the chunk range for a given path."""
        start = (path.number_always // self.__chunk_size) * self.__chunk_size
        end = start + self.__chunk_size - 1
        return start, end


# Methods


def autorename_files(args: Any) -> None:
    """Autorename files in a folder to be numbered sequentially."""
    renamer = Renamer(args)
    chunker = Chunker(args)

    for file, _, event_time in watch_directory(args.folder, args.extensions_regex):
        renamer.handle_file_event(file, event_time)
        chunker.handle_file_event(renamer.get_renamed_files())


# Numbering


def get_current_number(paths: Collection[NumberedPath]) -> int:
    """Returns what the current number is, given a set of numbered paths."""
    if len(paths) == 0:
        return 0
    return max(x.number_always for x in paths)


def get_next_number(paths: Collection[NumberedPath]) -> int:
    """Returns what the next number should be, given a set of numbered paths."""
    if len(paths) == 0:
        return 0
    return get_current_number(paths) + 1


def get_next_subnumber(paths: Collection[NumberedPath]) -> int:
    """Returns what the next subnumber should be, given a set of numbered paths."""
    if len(paths) == 0:
        return 0
    # Ensure all paths have the same number
    first = next(iter(paths))
    assert all(
        x.number == first.number for x in paths
    ), "Subnumber can only be computed on paths with the same number."
    # If there is an un-subnumbered file, pretend it's a -1 subnumber
    # (meaning that -0 is the next subnumber)
    return max(x.subnumber or -1 for x in paths) + 1


# File monitoring


def watch_directory(
    folder: Path,  # The folder to monitor.
    extensions_regex: re.Pattern,  # The file extensions to monitor.
) -> Generator[Tuple[NumberedPath, FileAction, float], None, None]:
    """Yields files, the action performed, and the time as they are
    added/moved to the directory."""

    last_move_from_time = 0
    for path, action, event_time in watch_directory_with_inotifywait(
        folder, extensions_regex
    ):
        # Renaming is a move from + to, so note the time if moved away...
        if action == FileAction.MOVED_FROM:
            last_move_from_time = event_time
            continue
        # ...and ignore files that were renamed inside the folder
        if (
            action == FileAction.MOVED_TO
            and last_move_from_time > event_time - RENAME_COOLDOWN
        ):
            last_move_from_time = 0
            continue
        last_move_from_time = 0
        # Yield the event because it's a new file or something moved in
        yield path, action, event_time


def watch_directory_with_inotifywait(
    folder: Path,  # The folder to monitor.
    extensions_regex: re.Pattern,  # The file extensions to monitor.
) -> Generator[Tuple[NumberedPath, FileAction, float], None, None]:
    """Returns the command needed to watch a directory."""
    command = [
        "inotifywait",
        "--monitor",
        "--event",
        "create,moved_from,moved_to",
        "--includei",
        extensions_regex.pattern,
        "--format",
        "%w%f,%e",
        "--timefmt",
        "%s",
        str(folder),
    ]
    for line in run_command(command):
        split = line.split(",")
        yield NumberedPath(split[0]), FileAction(split[1]), time.time()


def wait_for_file_locks(file: Path) -> None:
    """Waits until no processes are currently using a file."""
    first_attempt = True
    while True:
        try:
            for _ in run_command(("fuser", str(file)), stderr=subprocess.DEVNULL):
                pass
            if first_attempt:
                print(f"{file.name} is in use by another process, waiting...")
                first_attempt = False
            time.sleep(LOCKED_FILE_LOOP_SECONDS)
        except subprocess.SubprocessError:
            if not first_attempt:
                print(f"{file.name} unlocked.")
            return


# I/O


def extensions_to_regex(extensions: Collection[str]) -> re.Pattern:
    """Converts a set of extensions into a regex pattern that matches files with
    those extensions. Matches everything if extensions is empty."""
    # Just match the end of the line if nothing is passed
    if len(extensions) == 0:
        return re.compile("$")
    # Convert all extensions into individual regex patterns...
    temp = set(f"\\.{x.removeprefix(".")}$" for x in extensions)
    # ...and join them together
    return re.compile("|".join(temp))


def run_command(command: Sequence[str], stderr=None) -> Generator[str, None, None]:
    """Runs a command, yielding each line of output."""
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=stderr)
    atexit.register(lambda: process.send_signal(signal.SIGTERM))

    # Yield each line of the command
    if process.stdout is not None:
        for line in iter(process.stdout.readline, b""):
            yield line.rstrip().decode("utf-8")

    # Exit unsuccessfully if the subprocess did
    process.communicate()
    if process.returncode != 0:
        raise subprocess.SubprocessError(
            f"Command {command} exited with exit code {process.returncode}."
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog=Path(__file__).name)
    parser.add_argument(
        "--chunk-size",
        type=int,
        default=-1,
        help="(Default: disabled) Organize files into subfolders of a specific size.",
    )
    parser.add_argument(
        "--pairing-window",
        type=float,
        default=-1,
        help='(Default: disabled) The number of seconds between autonaming files where they will be considered a "pair" and given the same base name.',
    )
    parser.add_argument("folder", type=Path, help="The folder to monitor for changes")
    parser.add_argument(
        "extensions",
        type=str,
        nargs="*",
        help="(Default: all files) File extensions to limit renaming to.",
    )
    args = parser.parse_args(sys.argv[1:])

    # Derivative values
    args.extensions_regex = extensions_to_regex(args.extensions)

    try:
        autorename_files(args)
    except KeyboardInterrupt:
        print(" Interrupting...")
