icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[icons]
icons = "awesome4"
[icons.overrides]
gpu = [
    "",
]

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:20) |"
short = " $title.str(max_w:10) |"

[[block]]
block = "sound"

[[block]]
block = "bluetooth"
mac = "88:C9:E8:58:F5:55"
format = " $icon{$percentage|} "
disconnected_format = " $icon{ $percentage|} "

[[block]]
block = "bluetooth"
mac = "AC:8E:BD:67:12:C5"
format = " $icon{$percentage|} "
disconnected_format = " $icon{ $percentage|} "

[[block]]
block = "net"
interval = 10
format = "^icon_net_wired ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K)"
inactive_format = "^icon_net_wired Disconnected"
[[block.click]]
button = "middle"
cmd = "network toggle"

[[block]]
block = "disk_space"
interval = 600
format = "$icon / $used/$total($percentage)"
path = "/"
warning = 20
alert = 10

[[block]]
block = "disk_space"
interval = 600
format = "$icon /home $used/$total($percentage)"
path = "/home"
warning = 20
alert = 10

[[block]]
block = "disk_space"
interval = 600
format = "$icon /home/dan/data $used/$total($percentage)"
path = "/home/dan/data"
warning = 20
alert = 10

[[block]]
block = "memory"
interval = 5
format = " $swap_used.eng(prefix:Mi)/$swap_total.eng(prefix:Mi)($swap_used_percents.eng(w:2))"
warning_swap = 1
critical_swap = 50

[[block]]
block = "memory"
interval = 5
format = "$icon $mem_used.eng(prefix:Mi)/$mem_total.eng(prefix:Mi)($mem_used_percents.eng(w:2))"
warning_mem = 50
critical_mem = 90

[[block]]
block = "cpu"
interval = 5
format = "$icon $barchart$utilization"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "temperature"
interval = 5
format = "$icon $average avg, $max max"
idle = 50
good = 70
info = 75
warning = 80

#idle = 50
#good = 70
#info = 75
#warning = 80

[[block]]
block = "nvidia_gpu"
interval = 5
format = " $power  $memory  $utilization  $temperature  $fan_speed"
idle = 50
good = 70
info = 75
warning = 80

[[block]]
block = "service_status"
service = "nvidia-fan-control"
active_format = "  "
inactive_format = "  "
inactive_state = "Warning"
[[block.click]]
button = "middle"
cmd = "xterm -e 'journalctl --unit nvidia-fan-control.service --follow --lines=3600 --output=cat'"

[[block]]
block = "time"
interval = 5
[block.format]
short = "$icon $timestamp.datetime(f:%R)"


[[block]]
block = "menu"
text = ""

[[block.items]]
display = "-&gt; Exit i3 &lt;-"
confirm_msg = "-&gt; Exit i3? &lt;-"
cmd = "i3-msg exit"

[[block.items]]
display = "-&gt; Sleep &lt;-"
cmd = "systemctl suspend"

[[block.items]]
display = "-&gt; Reboot &lt;-"
confirm_msg = "-&gt; Reboot? &lt;-"
cmd = "reboot"

[[block.items]]
display = "-&gt; Shut down &lt;-"
confirm_msg = "-&gt; Shut down? &lt;-"
cmd = "shutdown now"
