#!/usr/bin/env bash
set -euo pipefail

SLEEP_SECONDS=30

while true; do

  echo 'Checking layout...'
  count="$(xrandr | grep --perl-regexp --count '^(DP-0 connected 3440x1440|HDMI-0 connected 3840x2160)')"
  if [[ "$count" -eq 2 ]]; then
    echo 'Layout fixed, exiting...'
    exit 0
  fi

  echo 'Executing xrandr command...'
  xrandr --output DP-0 \
    --mode 3440x1440 --rate 100.00 \
    --output HDMI-0 \
    --auto --below DP-0 --mode 3840x2160 --rate 59.94 \
  || true

  echo "Layout still incorrect, attempting fix again in $SLEEP_SECONDS seconds..."
  sleep "$SLEEP_SECONDS"
done
