#!/usr/bin/env python3
from collections.abc import Callable
from openrazer.client.devices.mice import RazerMouse

import argparse
import json
import math
import openrazer.client
import re
import sys

MIN_DPI = 100
MODIFIER_REGEX = re.compile(r"(?P<symbol>[-+*/]?)(?P<number>\d+(\.\d+)?)")

DEFAULT_DPI = 4000
BAR_CHARS = " ▁▂▃▄▅▆▇█"

DEVICE_MANAGER = openrazer.client.DeviceManager()


def list_devices() -> None:
    print("\n".join(sorted(x.name for x in DEVICE_MANAGER.devices)))


def get_device(name: str) -> None:
    devices = [x for x in DEVICE_MANAGER.devices if x.name == name]
    match len(devices):
        case 0:
            error(f"No devices found matching name '{name}'.")
        case 1:
            return devices[0]
        case _:
            error(f"More than 1 device found matching name '{name}'.")


def get_device_info(device: Any, format: str) -> str:
    """Returns a string of device info."""
    match format:
        case "text":
            return f"{device.dpi[0]}dpi"
        case "bar":
            return get_mouse_dpi_as_bar(device)
        case "i3status-bar":
            value = get_normalized_mouse_dpi(device)
            return (
                "{"
                f'"text":"{num_to_bar(value)}",'
                f'"state":"{get_mouse_dpi_as_i3_state(device)}"'
                "}"
            )
        case "i3status-text":
            return (
                "{"
                f'"text":"{device.dpi[0]}dpi",'
                f'"state":"{get_mouse_dpi_as_i3_state(device)}"'
                "}"
            )
        case _:
            RuntimeError(f"Unknown format '{format}'.")


def set_dpi(mouse: RazerMouse, modifier: str) -> None:
    """Changes the DPI of a mouse. Modifier can be one of +-*/ or an empty
    string followed by a number.

    Note: Results will be rounded to the closest integer within [MIN_DPI, mouse.max_dpi]
    """
    if not isinstance(mouse, RazerMouse):
        error(f"Cannot set DPI on non-mouse device '{mouse.name}'.")
    if not mouse.has("dpi"):
        error(f"Cannot set DPI on mouse without dpi attribute.")
    if min(mouse.dpi) != max(mouse.dpi):
        error(f"Cannot set DPI on mouse with non-uniform DPI value '{mouse.dpi}'.")

    prev = mouse.dpi[0]
    new = modify_number(prev, modifier, MIN_DPI, mouse.max_dpi, 0)
    print(f"DPI: {prev} -> {new}")
    mouse.dpi = new, new


def set_poll_rate(device: RazerMouse, poll_rate: int) -> None:
    if not device.has("poll_rate"):
        error(f"Cannot set poll rate on device without poll_rate attribute.")
    if poll_rate not in device.supported_poll_rates:
        error(
            f"Cannot set poll rate to unsupported value '{poll_rate}', value must be on of {device.supported_poll_rates}. "
        )

    print(f"Poll rate: {device.poll_rate} -> {poll_rate}")
    device.poll_rate = poll_rate


# Helpers


def get_normalized_mouse_dpi(mouse: RazerMouse) -> str:
    """Returns the DPI as a normalized value."""
    dpi = mouse.dpi[0]
    # 0 to 1/3
    if dpi < DEFAULT_DPI:
        curr_power = math.log2(dpi / MIN_DPI)
        max_power = math.log2(DEFAULT_DPI / MIN_DPI)
        return curr_power / (3 * max_power)
    # 1/3
    elif dpi == DEFAULT_DPI:
        return 1 / 3
    # 1/3 to 1
    else:
        curr_power = math.log2(dpi / DEFAULT_DPI)
        max_power = math.log2(mouse.max_dpi / DEFAULT_DPI)
        return 1 / 3 + (2 * curr_power) / (3 * max_power)


def get_mouse_dpi_as_i3_state(mouse: RazerMouse) -> str:
    """Returns the DPI of a mouse as a i3status-rust status."""
    # Easy cases
    dpi = mouse.dpi[0]
    if dpi == MIN_DPI:
        return "Critical"
    elif dpi < DEFAULT_DPI:
        return "Info"
    elif dpi == DEFAULT_DPI:
        return "Idle"
    elif dpi == mouse.max_dpi:
        return "Critical"

    # Above default
    factor = (mouse.max_dpi / DEFAULT_DPI) ** (0.5)
    if dpi < DEFAULT_DPI * factor:
        return "Good"
    else:
        return "Warning"


def num_to_bar(number: int | float, max_value: int | float = 1) -> str:
    """Converts a number to a vertical bar character."""
    float_index = number * (len(BAR_CHARS) - 1) / max_value
    int_index = max(0, min(math.floor(float_index), len(BAR_CHARS)))
    return BAR_CHARS[int_index]


def modify_number(
    original: int | float,  # The original value.
    modifier: str,  # The modifier of the value.
    min_value: int | float | None = None,  # The minimum value.
    max_value: int | float | None = None,  # The maximum value.
    round_to: int = 0,  # The decimal point to round to.
) -> int | float:
    """Modifies a number by a modifier.

    Modifier format:
    <number>     - Replaces the original number with the given number.
    +-*/<number> - Adds, subtracts, multiplies, or divides the original number.
    """
    match = MODIFIER_REGEX.fullmatch(modifier)
    if match is None:
        raise RuntimeError(f"Invalid modifier {modifier}.")

    # Modify value
    symbol = match.group("symbol")
    number = float(match.group("number"))

    # Ensure multiplication is making the value larger and division is making smaller.
    if number < 1 and symbol == "*":
        number = 1 / number
        symbol = "/"
    elif number < 1 and symbol == "/":
        number = 1 / number
        symbol = "*"

    # Snap to values integer multiples/powers of the modifier. In other words,
    # perform the operation as normal, but stop early at the first number that
    # is an integer multiple of the number when using +- or an integer power of
    # the number when using */

    match symbol:
        case "":
            x = number
        case "+":
            diff = original - DEFAULT_DPI
            # Pull the original down to the last DEFAULT_DPI + i*number, then add
            x = original - diff % number + number
        case "-":
            diff = original - DEFAULT_DPI
            # Pull the original up to the last DEFAULT_DPI + i*number, then subtract
            x = original + (-diff % number) - number
        case "*":
            factor = original / DEFAULT_DPI
            # Find the power for original * number = DEFAULT_DPI * number ** power
            power = math.log(factor * number, number)
            # Round the power down, allowing for floating point errors
            power = math.floor(round(power, 5))
            # Use the right side of the equation with the rounded power
            x = math.ceil(DEFAULT_DPI * number**power)
        case "/":
            factor = original / DEFAULT_DPI
            # Find the power for original / number = DEFAULT_DPI * number ** power
            power = math.log(factor / number, number)
            # Round the power up, allowing for floating point errors
            power = math.ceil(round(power, 5))
            # Use the right side of the equation with the rounded power
            x = math.floor(DEFAULT_DPI * number**power)
        case _:
            error(f"Unexpected symbol {symbol}.")

    # Round and min/max
    if round_to is not None:
        x = round(x, round_to)
    if min_value is not None:
        x = max(x, min_value)
    if max_value is not None:
        x = min(x, max_value)

    # Ensure type match with original
    if isinstance(original, int):
        x = int(x)
    elif isinstance(original, float):
        x = float(x)
    return x


def regex_type(pattern: re.Pattern) -> Callable[[str], re.Match]:
    """Generates an argparse type that ensures the value matches a regex pattern."""

    def check(x: str) -> re.Match:
        if not pattern.fullmatch(x):
            error(f"Value '{x}' does not match pattern '{pattern.pattern}'.")
        return x

    return check


def error(message: str) -> None:
    print(f"Error: {message}")
    sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="mouse",
        description="A basic CLI for managing a mouse.",
        epilog=(
            'Snapping note: to make DPI values more consistent, this tool "snaps"'
            " the dpi value using the following logic:"
            " when modifying the dpi with + or -, the value will"
            f' "snap" to the closest value that is {DEFAULT_DPI} +/- an integer'
            " multiple of the number provided."
            f" For example, if the current dpi was {DEFAULT_DPI+3} and"
            f" --dpi +5 was passed, the dpi would increase to {DEFAULT_DPI+5}"
            f" because {DEFAULT_DPI+5} = {DEFAULT_DPI} + 5 * 1."
            ' Similarly, when using * or /, the value will "snap" to'
            f" {DEFAULT_DPI} */ an integer power of the number provided."
        ),
    )
    parser.add_argument(
        "subcommand",
        choices=("help", "list", "get", "set"),
        help="The action to perform. Can be help, list, get, or set.",
    )
    parser.add_argument(
        "device_name",
        nargs="?",
        help="The name of the device. If unspecified, lists the devices by name instead.",
    )
    parser.add_argument(
        "--dpi",
        type=regex_type(MODIFIER_REGEX),
        help="Set the DPI of the mouse. Can be prefixed with +-*/ - See note about snapping below.",
    )
    parser.add_argument(
        "--format",
        choices=("text", "bar", "i3status-bar", "i3status-text"),
        default="text",
        help="The output format of the get command.",
    )
    parser.add_argument("--poll-rate", type=int, help="Set the poll rate of the mouse.")

    args = parser.parse_args()

    if args.subcommand in ("get", "set"):
        if args.device_name is None:
            error("Device name is required when using the get or set commands.")

    match args.subcommand:
        case "help":
            parser.print_help()
            sys.exit(1)
        case "list":
            list_devices()
        case "get":
            device = get_device(args.device_name)
            print(get_device_info(device, args.format))
        case "set":
            device = get_device(args.device_name)
            if args.dpi:
                set_dpi(device, args.dpi)
            if args.poll_rate:
                set_poll_rate(device, args.poll_rate)
