#!/usr/bin/env bash
set -euo pipefail

INTERFACE="eno2"

action="${1:-}"

if [[ ! "$action" =~ ^(up|down|toggle)$ ]]; then
  echo "Error: action '$action' can only be 'up', 'down', or 'toggle'."
  exit 1
fi

state="$(networkctl list "$INTERFACE" --json=short | jq -r .OnlineState)"

case "$state" in
online)
  case "$action" in
  up)
    echo "$INTERFACE is already up";;
  down|toggle)
    sudo networkctl down "$INTERFACE"
    echo "Set $INTERFACE down";;
  esac;;

offline)
  case "$action" in
  up|toggle)
    sudo networkctl up "$INTERFACE"
    echo "Set $INTERFACE up";;
  down)
    echo "$INTERFACE is already down";;
  esac;;
*)
  echo "Error: Unknown interface status '$state'."
  exit 1;;
esac
