#!/usr/bin/env bash
set -euo pipefail

IMAGE_DIR="$HOME/.config/i3/backgrounds"

if [[ ! -d "$IMAGE_DIR" ]]; then
  echo "Error: image directory $IMAGE_DIR does not exist."
  exit 1
fi

# Get the current background (or output an invalid path character if one isn't found)
current_image="$(
  grep --perl-regexp --only-matching "(?<=').*(?=')" "$HOME/.fehbg" \
  || echo '|'
)"

image="$(
  find "$IMAGE_DIR" -type f '(' \
    -name '*.jpg' -or -name '.jpeg' -or -name '*.png' \
  ')' \
  | grep --invert-match --fixed-strings "$current_image" \
  | shuf -n 1
)"

if [[ -z "$image" ]]; then
  echo "Error: no .jpg/.jpeg/.png files found in $IMAGE_DIR."
  exit 1
fi

feh --bg-fill "$image"
echo "Set background to $image"

