#!/bin/sh

# Keymap
xmodmap "/home/dan/.Xmodmap"

# Set background
~/.fluxbox/setbackground.sh

# Start VirtualBox guest additions
if command -v VBoxClient-all; then
  VBoxClient-all
fi

# Clock
lal &

# Run fluxbox
exec fluxbox
# exec fluxbox -log "/home/dan/.fluxbox/log"
