#!/bin/sh

POLKIT_AGENT="/usr/lib/polkit-kde-authentication-agent-1"

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi
if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi
if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi
if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# transparency
#xcompmgr &

# Set background
feh --bg-scale "$HOME/.config/i3/background.png"

# Run polkit auth agent in background
if [ -x "$POLKIT_AGENT" ]; then
  "$POLKIT_AGENT" &
fi

#exec startfluxbox
exec i3
