#!/usr/bin/env bash
set -e

function main {
  branch="$(git branch --show-current)"
  if [[ -z "$branch" ]]; then
    echo "Not currently on a branch!"
    return 1
  fi
  if git config --get-regex "branch\.$branch\.remote" > /dev/null; then
    echo 'Upstream already set'
  else
    git branch --set-upstream-to="origin/$branch" "$branch"
  fi
}

main "$@"
