#!/usr/bin/env bash
set -euo pipefail

MAC='88:C9:E8:58:F5:55'

action="${1:-}"

if [[ ! "$action" =~ ^(connect|disconnect|toggle)$ ]]; then
  echo "Error: action '$action' can only be 'connect', 'disconnect', or 'toggle'."
  exit 1
fi


# Already connected
if bluetoothctl endpoint.list | grep --quiet "${MAC//:/_}"; then
  case "$action" in
  connect)
    echo "Already connected to $MAC";;
  disconnect|toggle)
    bluetoothctl disconnect "$MAC";;
  esac

# Already disconnected
else
  case "$action" in
  connect|toggle)
    bluetoothctl connect "$MAC";;
  disconnect)
    echo "Already disconnected from $MAC";;
  esac
fi
